#!/bin/sh

rm -f *.o
rm -f remctl remctld

/usr/pubsw/bin/gcc -Wall -g -DHAVE_LIBNSL=1 -DHAVE_LIBSOCKET=1 -DKRB5_DNS_LOOKUP_KDC=1 -DKRB5_DNS_LOOKUP=1 -DHAVE_UNISTD_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1  -DUSE_AUTOCONF_H -DGSSAPI_V2 -DKRB5_KRB4_COMPAT -I../../include -I./../../include -I../../include/krb -I../../include/krb5 -I./../../include/krb5   -c gss-utils.c


/usr/pubsw/bin/gcc -Wall -g -DHAVE_LIBNSL=1 -DHAVE_LIBSOCKET=1 -DKRB5_DNS_LOOKUP_KDC=1 -DKRB5_DNS_LOOKUP=1 -DHAVE_UNISTD_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1  -DUSE_AUTOCONF_H -DGSSAPI_V2 -DKRB5_KRB4_COMPAT -I../../include -I./../../include -I../../include/krb -I../../include/krb5 -I./../../include/krb5   -c remctld.c


/usr/pubsw/bin/gcc -Wall -g -DHAVE_LIBNSL=1 -DHAVE_LIBSOCKET=1 -DKRB5_DNS_LOOKUP_KDC=1 -DKRB5_DNS_LOOKUP=1 -DHAVE_UNISTD_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1  -DUSE_AUTOCONF_H -DGSSAPI_V2 -DKRB5_KRB4_COMPAT -I../../include -I./../../include -I../../include/krb -I../../include/krb5 -I./../../include/krb5   -c remctl.c


gcc -g -o remctld remctld.o gss-utils.o -lgssapi_krb5 -lsocket -lnsl -lresolv
gcc -g -o remctl gss-utils.o remctl.o -lgssapi_krb5 -lsocket -lnsl -lresolv

