#!/bin/sh
#
# This is the (reformatted) output from autodep8 on the source package,
# specified here since autodep8 appears not to run if tests/control exists,
# thus requiring the test be specified manually.

set -e
for py in $(pyversions -r 2>/dev/null) $(py3versions -r 2>/dev/null); do
    cd "$AUTOPKGTEST_TMP"
    echo "Testing with $py:"
    $py -c "from __future__ import print_function; import remctl; print(remctl)"
done
