# Perl dependencies for CI tests.   -*- perl -*-
#
# This file is used by cpanm to install dependencies used by the remctl test
# suite.
#
# Copyright 2016, 2018-2020 Russ Allbery <eagle@eyrie.org>
#
# SPDX-License-Identifier: MIT

on 'test' => sub {
    requires 'Module::Build';
    suggests 'Devel::Cover';
    suggests 'Test::MinimumVersion';
    suggests 'Test::Perl::Critic';
    suggests 'Test::Pod';
    suggests 'Test::Pod::Coverage';
    suggests 'Test::Spelling';
    suggests 'Test::Strict';
    suggests 'Test::Synopsis';
}
