#!/bin/sh
case "$1" in
help)
    case "$2" in
    subhelp)    echo "subhelp text" ;;
    *)          echo "help text" ;;
    esac ;;
summary) 
    case "$2" in
    subcommand) echo "subcommand summary" ;;
    *)          echo "summary text" ;;
    esac ;;
*)
    echo "requested '$1' for help"
    exit 1
    ;;
esac
exit 0
